SAC/SAC/Controllers/ProvinciaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//agregadas
using AutoMapper;
using Negocio.Modelos;
using Negocio.Servicios;
using SAC.Atributos;
using SAC.Models;
using System.Web.Routing;

namespace SAC.Controllers
{
    public class ProvinciaController : BaseController
    {
        private ServicioProvincia servicioProvincia = new ServicioProvincia();


        public ProvinciaController()
        {
            servicioProvincia._mensaje = (msg_, tipo_) => CrearTempData(msg_, tipo_);
        }

        // GET: Provincia
        public ActionResult Index(ProvinciaModelView oProvinciaModel)
        {
            CargarPais();

            int idPais = oProvinciaModel.idCmbPais;

            if (idPais == 0) {
                List<ProvinciaModelView> provinciaModelView = Mapper.Map<List<ProvinciaModel>, List<ProvinciaModelView>>(servicioProvincia.GetAllProvincias());
                return View(provinciaModelView);
            }
            else
            {
                List<ProvinciaModelView> provinciaModelView = Mapper.Map<List<ProvinciaModel>, List<ProvinciaModelView>>(servicioProvincia.GetAllProvincias(idPais));
                return View(provinciaModelView);
            }
        
          
        }

        public ActionResult Agregar()
        {
            CargarPais();
            return View();
        }

        [HttpPost]
        public ActionResult Agregar(ProvinciaModelView oProvinciaModelView)
        {
            CargarPais();
            int respuesta = -1;
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(oProvinciaModelView);
                }
                else
                {
                    var datosUsuario = (UsuarioModel)System.Web.HttpContext.Current.Session["currentUser"];
                    ProvinciaModel oProvincia = new ProvinciaModel();
                    var oProvinciaModel = Mapper.Map<ProvinciaModelView, ProvinciaModel>(oProvinciaModelView);

                    oProvincia.Nombre = oProvinciaModel.Nombre;
                    oProvincia.Codigo = oProvinciaModel.Codigo;
                    oProvincia.CodigoNumero = oProvinciaModel.CodigoNumero;
                    oProvincia.IdPais = oProvinciaModel.IdPais;
                    oProvincia.CodigoAfip = oProvinciaModel.CodigoAfip;
                    
                    oProvincia.Activo = true;
                    oProvincia.IdUsuario = datosUsuario.IdUsuario;//hay que poner el id del usuario logueado
                    oProvincia.UltimaModificacion = DateTime.Now.Date;

                    respuesta = servicioProvincia.GuardarProvincia(oProvincia);

                    if (respuesta == 0) //grabo
                    {
                        servicioProvincia._mensaje("El país se registró correctamente", "ok");
                    }
                    else if (respuesta == -1) // paso algo
                    {
                        servicioProvincia._mensaje("El país ingresado No se pudo registrar", "error");
                    }
                    else //ya existe
                    {
                        servicioProvincia._mensaje("El país que intenta resitrar ya se encuentra cargado", "error");
                    }
                    return RedirectToAction("Index");
                }

            }
            catch (Exception ex)
            {
                servicioProvincia._mensaje(ex.Message, "error");
                return View(oProvinciaModelView);
            }


          
        }

        public ActionResult Editar(int _id)
        {
            CargarPais();
            ProvinciaModelView oPovinciaModel = new ProvinciaModelView();
            oPovinciaModel = Mapper.Map<ProvinciaModel, ProvinciaModelView>(servicioProvincia.GetProvincia(_id));
            return View(oPovinciaModel);
           
        }

        [HttpPost]
        public ActionResult Editar(ProvinciaModelView oProvinciaModelView)
        {
            int respuesta = -1;
            CargarPais();

            try
            {
                if (!ModelState.IsValid)
                {
                    return View(oProvinciaModelView);
                }
                else
                {
                    var datosUsuario = (UsuarioModel)System.Web.HttpContext.Current.Session["currentUser"];

                    ProvinciaModel oProvinciaModel = new ProvinciaModel();
                    var oProvincia = Mapper.Map<ProvinciaModelView, ProvinciaModel>(oProvinciaModelView);

                    oProvinciaModel.Id = oProvincia.Id;
                    oProvinciaModel.Nombre = oProvincia.Nombre;
                    oProvinciaModel.Codigo = oProvincia.Codigo;
                    oProvinciaModel.CodigoAfip = oProvincia.CodigoAfip;
                    oProvinciaModel.CodigoNumero = oProvincia.CodigoNumero;
                    oProvinciaModel.IdPais = oProvincia.IdPais;
                    oProvinciaModel.Activo = true;
                    oProvinciaModel.IdUsuario = datosUsuario.IdUsuario;//hay que poner el id del usuario logueado
                    oProvinciaModel.UltimaModificacion = DateTime.Now.Date;


                    respuesta = servicioProvincia.ActualizarPais(oProvinciaModel);

                    if (respuesta == 0) //grabo
                    {
                        servicioProvincia._mensaje("El país se registró correctamente", "ok");
                    }
                    else if (respuesta == -1) // paso algo
                    {
                        servicioProvincia._mensaje("El país ingresado No se pudo registrar", "error");
                    }
                    else //-2 existe
                    {
                        servicioProvincia._mensaje("El país que intenta resitrar ya se encuentra cargado", "error");
                    }

                    return RedirectToAction("Index");
                }
            }

            catch (Exception ex)
            {
                servicioProvincia._mensaje(ex.Message, "error");
                return View(oProvinciaModelView);
            }
        }

        [HttpPost]
        public ActionResult Eliminar(int idProvincia)
        {
            try
            {
                servicioProvincia.Eliminar(idProvincia);
                servicioProvincia._mensaje("El país se eliminó correctamente", "ok");
            }
            catch (Exception ex)
            {
                servicioProvincia._mensaje(ex.Message, "error");
            }

            return RedirectToAction("Index");
        }

        //combo pais
        public void CargarPais()
        {

            ServicioPais servicioPais = new ServicioPais();
            List<PaisModelView> ListaPais = Mapper.Map<List<PaisModel>, List<PaisModelView>>(servicioPais.GetAllPais());
            //ListaPais = ListaPais.OrderBy(p => p.Nombre).ToList();
            //esto es para pasarlo a select list (drop down list)
            List<SelectListItem> retornoListaPais = null;
            retornoListaPais = (ListaPais.Select(x =>
                                  new SelectListItem()
                                  {
                                      Value = x.Id.ToString(),
                                      Text = x.Nombre
                                  })).ToList();
            retornoListaPais.Insert(0, new SelectListItem { Text = "--Seleccione País--", Value = "" });


            ViewBag.Listapagina = retornoListaPais;
        }

       

    }
}

SAC/SAC/Views/Provincia/Agregar.cshtml
@model SAC.Models.ProvinciaModelView

@{
    ViewBag.Title = "Agregar Provincia";
    Layout = "~/Views/Shared/_Layout.cshtml";

    List<SelectListItem> ListaPais = (List<SelectListItem>)ViewBag.Listapagina;
}

<!-- ============================================================== -->
<!-- Bread crumb and right sidebar toggle -->
<!-- ============================================================== -->
<div class="row page-titles m-t-40">
    <div class="col-md-5 align-self-center">
        <h3 class="text-themecolor">Agregar Provincias</h3>
    </div>
</div>

<div class="row">
    <div class="col-xlg-12 col-lg-12 col-md-12">
        <div class="card">
            <div class="card-body">

                <div class="row">
                    <div class="col-md-3"></div>
                    <div class="col-md-6">

                        @using (Html.BeginForm("Agregar", "Provincia", FormMethod.Post, new { @id = "frmBusqueda" }))
                        {

                            <div>
                                @*@Html.LabelFor(p => p.Id)
                                @Html.TextBoxFor(p => p.Id, new { @class = "hide" })*@

                                @Html.LabelFor(p => p.Nombre)
                                @Html.TextBoxFor(p => p.Nombre, new { @class = "form-control", @placeholder = "Ej: Lituania" })
                                @Html.ValidationMessage("Nombre", new { @class = "text-danger" })

                            </div>
                            <div style="margin-top:1em">
                                @Html.LabelFor(p => p.IdPais)
                                @Html.DropDownList("idPais", ListaPais, null, new { @class = "form-control" })
                                @Html.ValidationMessage("idPais", new { @class = "text-danger" })
                            </div>
                            <div style="margin-top:1em">
                                @Html.LabelFor(p => p.Codigo)
                                @Html.EditorFor(p => p.Codigo, new { htmlAttributes = new { @class = "form-control", @placeholder = "00-0000-00" } })
                                @Html.ValidationMessage("Codigo", new { @class = "text-danger" })
                            </div>
                            <div style="margin-top:1em">
                                @Html.LabelFor(p => p.CodigoNumero)
                                @Html.EditorFor(p => p.CodigoNumero, new { htmlAttributes = new { @type = "number", @min = "0", @class = "form-control", @placeholder = "00-0000-00" } })
                                @Html.ValidationMessage("CodigoNumero", new { @class = "text-danger" })
                            </div>
                            <div style="margin-top:1em">
                                @Html.LabelFor(p => p.CodigoAfip)
                                @Html.EditorFor(p => p.CodigoAfip, new { htmlAttributes = new { @type = "number", @min = "0", @class = "form-control", @placeholder = "000000" } })
                                @Html.ValidationMessage("CodigoAfip", new { @class = "text-danger" })
                            </div>

                            <br />
                            <div style="margin:auto">
                                <input type="submit" class="btn btn-primary" value="Guardar" />
                                @Html.ActionLink("Volver", "Index", "Provincia", null, new { @class = "btn btn-primary" })
                            </div>

                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

SAC/SAC/Views/Provincia/Editar.cshtml
@model SAC.Models.ProvinciaModelView


@{
    ViewBag.Title = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<SelectListItem> ListaPais = (List<SelectListItem>)ViewBag.Listapagina;
}

<!-- ============================================================== -->
<!-- Bread crumb and right sidebar toggle -->
<!-- ============================================================== -->
<div class="row page-titles m-t-40">
    <div class="col-md-5 align-self-center">
        <h3 class="text-themecolor">Editar Provincia</h3>
    </div>

</div>


<div class="row">
    <div class="col-xlg-12 col-lg-12 col-md-12">
        <div class="card">
            <div class="card-body">

                <div class="row">
                    <div class="col-md-3"></div>
                    <div class="col-md-6">
                        @using (Html.BeginForm("Editar", "Provincia", FormMethod.Post))
                        {
                        <div>

                            @Html.LabelFor(p => p.Id, new { @class = "hide" })
                            @Html.TextBoxFor(p => p.Id, new { @class = "hide" })

                            @Html.LabelFor(p => p.Nombre)
                            @Html.TextBoxFor(p => p.Nombre, new { @class = "form-control" })
                            @Html.ValidationMessage("Nombre", new { @class = "text-danger" })

                        </div>

                            <div style="margin-top:1em">
                                @Html.LabelFor(p => p.IdPais)
                                @Html.DropDownList("idPais", ListaPais, null, new { @class = "form-control" })
                                @Html.ValidationMessage("idPais", new { @class = "text-danger" })
                            </div>

                            <div style="margin-top:1em">
                                @Html.LabelFor(p => p.Codigo)
                                @Html.TextBoxFor(p => p.Codigo, new { @class = "form-control" })
                                @Html.ValidationMessage("Codigo", new { @class = "text-danger" })
                            </div>

                            <div style="margin-top:1em">
                                @Html.LabelFor(p => p.CodigoNumero)
                                @Html.EditorFor(p => p.CodigoNumero, new { htmlAttributes = new { @type = "number", @min = "0", @class = "form-control"} })
                                @Html.ValidationMessage("CodigoNumero", new { @class = "text-danger" })
                            </div>

                            <div style="margin-top:1em">
                                @Html.LabelFor(p => p.CodigoAfip)
                                @Html.EditorFor(p => p.CodigoAfip, new { htmlAttributes = new { @type = "number", @min = "0", @class = "form-control", @placeholder = "000000" } })
                                @Html.ValidationMessage("CodigoAfip", new { @class = "text-danger" })
                            </div>


                            <br />
                            <div style="margin:auto">
                                <input type="submit" class="btn btn-primary" value="Guardar" />
                                @Html.ActionLink("Volver", "Index", "Provincia", null, new { @class = "btn btn-primary" })
                            </div>

                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

SAC/SAC/Views/Provincia/Index.cshtml
@model List<SAC.Models.ProvinciaModelView>

@{
    ViewBag.Title = "Lista Provincia";
    Layout = "~/Views/Shared/_Layout.cshtml";

    List<SelectListItem> ListaPais = (List<SelectListItem>)ViewBag.Listapagina;

}

<!-- ============================================================== -->
<!-- Bread crumb and right sidebar toggle -->
<!-- ============================================================== -->
<div class="row page-titles m-t-40">
    <div class="col-md-5 align-self-center">
        <h3 class="text-themecolor">Lista de Provincias</h3>
    </div>
</div>
<div class="row">
    <div class="col-xlg-12 col-lg-12 col-md-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Exportar datos</h4>
                <h6 class="card-subtitle">Formato de salida: PDF</h6>
                <div class="table-responsive m-t-40">

                    @Html.ActionLink("Nuevo", "Agregar", "Provincia", new { @class = "btn btn-primary" })



                    @using (Html.BeginForm("Index", "Provincia", FormMethod.Get, new { @id = "frmBusqueda" }))
                    {
                        <br />
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    @Html.Label("Seleccione un país")
                                    @Html.DropDownList("idCmbPais", ListaPais, null, new { @class = "form-control" })
                                </div>
                            </div>
                        </div>


                        <table id="tblPais" class="display nowrap table table-hover table-striped table-bordered" cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    <th> Nombre</th>
                                    <th> Codigo</th>
                                    <th>Pais</th>
                                    <th>Operaciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@Html.DisplayFor(modelItem => item.Nombre)</td>
                                        <td>@Html.DisplayFor(modelItem => item.Codigo)</td>
                                        <td>@Html.DisplayFor(modelItem => item.Pais.Nombre)</td>
                                        <td>
                                            @Html.ActionLink(" ", "Editar", "Provincia", new { _id = @item.Id }, new { @class = "btn btn-primary fa fa-pencil-square-o" })
                                            @Html.ActionLink(" ", "Eliminar", "Provincia", new { _id = @item.Id }, new { @class = "btn btn-danger fa fa-trash-o", onclick = "AsigarConfirmacion(" + @item.Id + ")" })

                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>

                    }
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="ModalConfirmacion" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Aviso</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="modal-body">
                <h3> ¿Está seguro que desea eliminar la Provincia seleccionada?</h3>
            </div>


            <div style="padding:1em;">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <button type="button" onclick="Eliminar()" class="btn btn-primary">Aceptar</button>

            </div>
        </div>
    </div>
</div>



@* crea un formulario para ir al controlador *@
@using (Html.BeginForm("Eliminar", "Provincia", FormMethod.Post, new { @id = "frmEliminar" }))
{
    @Html.Hidden("idProvincia");
}


<script>

    var idtipoUsuario = document.getElementById("idCmbPais")
    idtipoUsuario.onchange = function () {
        var frmBusquda = document.getElementById("frmBusqueda");
        frmBusquda.submit();
    }


    function AsigarConfirmacion(idProvincia) {
        event.preventDefault();
        document.getElementById("idProvincia").value = idProvincia;
        //console.log(idPais);
        $("#ModalConfirmacion").modal('show');
    }


    function Eliminar() {
        var frmEliminar = document.getElementById("frmEliminar");
        frmEliminar.submit();
    }

</script>

@section Scripts{

    <!-- This is data table -->
    <script src="/Content/assets/plugins/datatables/jquery.dataTables.min.js"></script>
    <!-- start - This is for export functionality only -->

    <script src="~/Content/assets/plugins/datatables/jsTable/dataTables.buttons.min.js"></script>
    <script src="~/Content/assets/plugins/datatables/jsTable/buttons.flash.min.js"></script>
    <script src="~/Content/assets/plugins/datatables/jsTable/jszip.min.js"></script>
    <script src="~/Content/assets/plugins/datatables/jsTable/pdfmake.min.js"></script>
    <script src="~/Content/assets/plugins/datatables/jsTable/vfs_fonts.js"></script>
    <script src="~/Content/assets/plugins/datatables/jsTable/buttons.html5.min.js"></script>
    <script src="~/Content/assets/plugins/datatables/jsTable/buttons.print.min.js"></script>


    <script type="text/javascript">
        $(document).ready(function () {
            $('#tblPais').DataTable({
                dom: 'Bfrtip',
                buttons: [
                    'pdf'
                ]
            });
        });



    </script>

}