SAC/SAC/Controllers/CajaGrupoController.cs
using Negocio.Servicios;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SAC.Atributos;
using SAC.Models;
using AutoMapper;
using Negocio.Modelos;

namespace SAC.Controllers
{
    public class CajaGrupoController : BaseController
    {

        private ServicioCajaGrupo serviciocajagrupo = new ServicioCajaGrupo();
        public CajaGrupoController()
        {            
            serviciocajagrupo._mensaje = (msg_, tipo_) => CrearTempData(msg_, tipo_);
        }


        // GET: Usuario
        public ActionResult Index()
        {
            List<CajaGrupoModelView> cajaGrupoModelViews = new List<CajaGrupoModelView>();
             cajaGrupoModelViews = Mapper.Map<List<CajaGrupoModel>, List<CajaGrupoModelView>>(serviciocajagrupo.GetAllCajaGrupo());
            return View(cajaGrupoModelViews);
        }

        public ActionResult AddOrEdit(int id = 0)
        {
            CajaGrupoModelView model;
            if (id == 0)
            {
                model = new CajaGrupoModelView();
            }
            else
            {
                model = Mapper.Map<CajaGrupoModel, CajaGrupoModelView>(serviciocajagrupo.GetGrupoCajaPorId(id));
                
            }

           // model.Roles = Mapper.Map<List<RolModel>, List<RolModelView>>(servicioConfiguracion.GetAllRoles());
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]         
        public ActionResult AddOrEdit(CajaGrupoModelView model)
        {
            try
            {        
            if (ModelState.IsValid)
            {

                    var OUsuario = (UsuarioModel)System.Web.HttpContext.Current.Session["currentUser"];
                    model.IdUsuario= OUsuario.IdUsuario;
                    //serviciocajagrupo._mensaje("","ok");
               if (model.Id <= 0)
                {
                   serviciocajagrupo.GuardarGrupoCaja(Mapper.Map<CajaGrupoModelView, CajaGrupoModel>(model));
                }
                else
                {
                    serviciocajagrupo.ActualizarGrupoCaja(Mapper.Map<CajaGrupoModelView, CajaGrupoModel>(model));
                }
                return RedirectToAction(nameof(Index));
            }
            return View(model);

            }
            catch (Exception)
            {
                return View(model);
            }
        }

        [HttpPost]
        public ActionResult Eliminar(int id)
        {
            try
            {
                serviciocajagrupo.Eliminar(id);
               
            }
            catch (Exception ex)
            {
                serviciocajagrupo._mensaje(ex.Message, "error");
            }

            return RedirectToAction("Index");
        }
   
        public ActionResult ConsultaGrupo()
        {


            List<CajaGrupoModelView> cajaGrupoModelViews = new List<CajaGrupoModelView>();
            cajaGrupoModelViews = Mapper.Map<List<CajaGrupoModel>, List<CajaGrupoModelView>>(serviciocajagrupo.GetAllCajaGrupo());
            return View(cajaGrupoModelViews);



        }

        [HttpPost]
        public ActionResult CajaGrupoCerrar()
        {
            try
            {
               serviciocajagrupo.CerrarGrupoCaja();
            }
            catch (Exception ex)
            {
                serviciocajagrupo._mensaje(ex.Message, "error");
            }
            return RedirectToAction("ConsultaGrupo");
        }


    }
}

SAC/SAC/Views/CajaGrupo/AddOrEdit.cshtml
@model SAC.Models.CajaGrupoModelView

@{
    ViewBag.Title = "AddOrEdit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    @Html.Hidden("BotonSeleccion")


<div class="form-horizontal">

    <div class="row">
        <!-- Column -->
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">

                    
                   
                        <div class="form-body">
                            <div class="row">


                                <div class="col-xlg-3 col-lg-4 col-md-4">
                                    <div class="form-group row">
                                        <small class="col-md-3">Codigo</small>
                                        <div class="col-md-9">
                                            @Html.EditorFor(model => model.Codigo, new { htmlAttributes = new { @class = "form-control form-control-sm" } })
                                            @Html.ValidationMessageFor(model => model.Codigo, "", new { @class = "text-danger" })


                                        </div>
                                    </div>
                                </div>


                                <div class="col-xlg-6 col-lg-4 col-md-4">
                                    <div class="form-group row">
                                        <small class="col-md-3">Concepto</small>
                                        <div class="col-md-9">
                                            @Html.EditorFor(model => model.Concepto, new { htmlAttributes = new { @class = "form-control form-control-sm" } })
                                            @Html.ValidationMessageFor(model => model.Concepto, "", new { @class = "text-danger" })


                                        </div>
                                    </div>
                                </div>




                                <div class="col-xlg-4 col-lg-4 col-md-4">
                                    <div class="form-group row">
                                        <small class="col-md-4">Imputacion</small>
                                        <div class="col-md-6">
                                            @Html.TextBoxFor(model => model.IdImputacion, new { @class = "form-control form-control-sm", @placeholder = "Ej: 00000", @readonly = true })
                                        </div> 
                                        <div class="col-md-2">
                                            <button type="button" id="btnImpProvBuscarFact" class="btn btn-primary fa fa-search" onclick="BuscarImputacion(1)"></button>


                                            <button id="btnCargandoFact" class="btn btn-primary" type="button" disabled style="display:none">
                                                <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
                                                Loading...
                                            </button>

                                        </div>
                                            <div class="col-md-2">
                                                    @Html.ValidationMessage("IdImputacion", new { @class = "text-danger" })
                                                </div>
                                            </div>
                                        
                                </div>


                            </div>
                        
                            <div class="form-actions m">

                                <button type="submit" class="btn btn-success btn-sm"> <i class="fa fa-check"></i> Guardar</button>


                                <button type="button" class="btn btn-dark btn-sm">Cancel</button>
                            </div>






                        </div>
                   
                </div>
            </div>
        </div>
        <!-- Column -->
    </div>




</div>




                    }

                    <div class="modal fade" id="exampleModal" style="overflow-y: auto;" tabindex="-1" role="dialog" aria-labelledby="exampleModalScrollableTitle" aria-hidden="true">
                        <div class="modal-dialog modal-lg modal-dialog-scrollable" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h4 class="modal-title" id="TituloModal">Seleccione un número de imputación</h4>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body text-center">
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div id="SubRubro">  </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-primary" data-dismiss="modal">Cancelar</button>
                                </div>
                            </div>
                        </div>
                    </div>


                    <script>


                        function AgregarImputacion(idSubRubro) {
                            var Seleccion = document.getElementById("BotonSeleccion").value;
                            if (Seleccion == "1") {
                                document.getElementById("IdImputacion").value = idSubRubro;
                            }


                            $("#exampleModal").modal('hide');
                        }

                        function BuscarImputacion(boton) {
                            document.getElementById("BotonSeleccion").value = boton;

                            var botonBuscar = "";
                            var botonCargando = "";

                            if (boton == "1") {
                                botonBuscar = "#btnImpProvBuscar";
                                botonCargando = "#btnCargando";
                            }
                            if (boton == "2") {
                                botonBuscar = "#btnImpProvBuscarFact";
                                botonCargando = "#btnCargandoFact";
                            }

                            $.ajax({
                                type: "POST",
                                url: "/Proveedor/CargarImputacion",
                                contentType: "application/json; charset=utf-8",
                                dataType: "html",
                                beforeSend: function () {
                                    $(botonBuscar).css("display", "none");
                                    $(botonCargando).css("display", "block");
                                }, complete: function () {
                                    $(botonBuscar).css("display", "block");
                                    $(botonCargando).css("display", "none");

                                },
                                success: function (response) {
                                    $('#SubRubro').html(response);
                                    $("#exampleModal").modal('show');
                                    fntabla();
                                },
                                failure: function (response) {
                                    Console.log(response.responseText);
                                },
                                error: function (response) {
                                    Console.log(response.responseText);
                                }
                            });

                        }
                        function fntabla() {

                            if ($.fn.dataTable.isDataTable('#tblImputacion')) {
                                table = $('#tblImputacion').DataTable();
                                table.destroy();
                                fntablaRenderizar();
                            } else {
                                fntablaRenderizar();
                            }
                        }
                        function fntablaRenderizar() {
                            $('#tblImputacion').DataTable({
                                "language": { "url": "/Content/assets/plugins/datatables/es.txt" },
                                "order": [[2, 'asc']],
                                'paging': true,
                                "scrollY": "300px",
                                'lengthChange': false,
                                'pageLength': 15,
                                'searching': true,
                                'ordering': true,
                                'info': false,
                                'autoWidth': true,
                                'dom': 'Bfrtip',
                                'buttons': []
                            });
                        }


                    </script>

                    @section Scripts{
                        <script src="~/Content/assets/plugins/datatables/jquery.dataTables.min.js"></script>
                        <!-- start - This is for export functionality only -->
                        <script src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
                        <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.flash.min.js"></script>
                        <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
                        <script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js"></script>
                        <script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js"></script>
                        <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.html5.min.js"></script>
                        <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.print.min.js"></script>

                    }

SAC/SAC/Views/CajaGrupo/ConsultaGrupo.cshtml
@model List<SAC.Models.CajaGrupoModelView>

@{
    ViewBag.Title = "Consulta - Cierre de Grupo Caja ";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<!-- ============================================================== -->
<!-- Bread crumb and right sidebar toggle -->
<!-- ==============================================================
<div class="row page-titles">
    <div class="col-md-5 align-self-center">
        <h4 class="text-themecolor">Consulta - Cierre Grupo Caja</h4>
    </div>

</div>
-->
<!-- ============================================================== -->
<!-- Start Page Content -->
<!-- ============================================================== -->
<div class="row">
    <div class="col-xlg-12 col-lg-12 col-md-12">

        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Consulta Totales por Grupo</h5>
                <h6 class="card-subtitle"> </h6>
                <div class="table-responsive m-t-40">

                    <table id="example23" class="table stylish-table">

                        <thead>
                            <tr>
                                <th>
                                    Codigo
                                </th>
                                <th>
                                    Descripcion
                                </th>
                                <th>
                                    P Pesos
                                </th>
                                <th>
                                    P Dolares
                                </th>
                                <th>
                                    P Cheques
                                </th>

                                <th>
                                    P Pesos
                                </th>
                                <th>
                                    T Dolares
                                </th>
                                <th>
                                    T Cheques
                                </th>
                                <th>Total</th>


                            </tr>
                        </thead>
                        <tbody>
                            @{
                                decimal? Total = 0;

                            }


                            @foreach (var item in Model)

                            {




                                Total = item.TotalPesos + item.TotalDolares + item.TotalCheques;

                                <tr class="@("table-" + item.Id)">


                                    <td>
                                        @Html.DisplayFor(modelItem => item.Codigo)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Concepto)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.ParcialPesos)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.ParcialDolares)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.ParcialCheques)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.TotalPesos)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.TotalDolares)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.TotalCheques)
                                    </td>



                                    <td>
                                        @Html.Raw(Total)
                                    </td>




                                </tr>
                            }

                        </tbody>

                    </table>
                </div>

                <div class="form-actions mt-5">

                    <span data-toggle="modal" data-target="#myModalEliminar">
                        <a class="btn btn-success btn-sm" role='button' data-toggle="tooltip" data-placement="top" title="Cerrar Caja">Cierre del Grupo Caja</a>
                    </span>


                    <button type="button" class="btn btn-dark btn-sm">Cancel</button>
                </div>
            </div>
        </div>

    </div>
</div>


<div class="modal fade" id="myModalEliminar" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="simpleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form method="post" role="form" action="CajaGrupoCerrar">
                <div class="modal-header">
                    <h4 class="modal-title" id="simpleModalLabel">Cerrar Grupo Caja</h4>
                </div>
                <div class="modal-body">
                    <input type="hidden" name="ID" id="Id" value="" />
                    <p>Esta seguro de que desea hace el Cierre del Grupo  Caja ?</p>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-raised btn-success">Confirmar</button>
                    <button type="button" class="btn btn-raised btn-default" data-dismiss="modal">Cancelar</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- ============================================================== -->
<!-- End PAge Content -->
<!-- ============================================================== -->






@section Scripts{

    <!-- ============================================================== -->
    <!-- Plugins for this page -->
    <!-- ============================================================== -->
    <!-- This is data table -->

    <script src="~/Content/assets/plugins/datatables/jquery.dataTables.min.js"></script>
    <!-- start - This is for export functionality only -->
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
    <script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js"></script>
    <script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.print.min.js"></script>

    <script type="text/javascript">


        $(function () {

            $('#example23').DataTable({
                "language": { "url": "../Content/assets/plugins/datatables/es.txt" },
                "order": [[2, 'asc']],
                'paging': true,
                'lengthChange': false,
                'searching': true,
                'ordering': true,
                'info': true,
                'autoWidth': true,
                'dom': 'Bfrtip',
                'buttons': [
                    'pdf'
                ]
            });
        });


        jQuery(function ($) {
            $('#myModalEliminar').on('show.bs.modal', function (e) {
                var id = $(e.relatedTarget).data().id;
                $(e.currentTarget).find('#Id').val(id);
            });
        });





    </script>
}

SAC/SAC/Views/CajaGrupo/Index.cshtml
@model List<SAC.Models.CajaGrupoModelView>

@{
    ViewBag.Title = "Caja";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<!-- ============================================================== -->
<!-- Start Page Content -->
<!-- ============================================================== -->
<div class="row">
    <div class="col-xlg-12 col-lg-12 col-md-12">

        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Lista de Grupos de Caja</h5>
                <h6 class="card-subtitle"> </h6>
                <a href="@Url.Action("AddOrEdit", "CajaGrupo")" class="btn btn-sm btn-secondary "><i class="mdi mdi-calendar-plus"></i> Nuevo Grupo</a>
                <div class="table-responsive m-t-40">

                    <table id="example23" class="table stylish-table">

                        <thead>
                            <tr>


                                <th>
                                    Codigo
                                </th>
                                <th>
                                    Descripcion
                                </th>
                                <th>
                                    Imputacion
                                </th>

                                <th>Acciones</th>


                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                            <tr class="@("table-" + item.Id)">

                               
                                <td>
                                    @Html.DisplayFor(modelItem => item.Codigo)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Concepto)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.IdImputacion)
                                </td>

                                <td>
                                    <a href="@Url.Action("AddOrEdit", "CajaGrupo",new { id = item.Id })" data-toggle="tooltip" data-original-title="Editar" class="btn btn-primary fa fa-pencil-square-o"></a>

                                   
                                    <span data-toggle="modal" data-target="#myModalEliminar" data-id="@Html.DisplayFor(modelItem =>item.Id)">
                                        <a class="btn btn-danger fa fa-trash-o" role='button' data-toggle="tooltip" data-placement="top" title="Eliminar">.</a>
                                    </span>
                                </td>




                            </tr>
                            }

                        </tbody>

                    </table>
                </div>
            </div>
        </div>

    </div>
</div>
<!-- ============================================================== -->
<!-- End PAge Content -->
<!-- ============================================================== -->




<div class="modal fade" id="myModalEliminar" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="simpleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form method="post" role="form" action="Eliminar">
                <div class="modal-header">
                    <h4 class="modal-title" id="simpleModalLabel">Eliminar Grupo Caja</h4>
                </div>
                <div class="modal-body">
                    <input type="hidden" name="ID" id="Id" value="" />
                    <p>Esta seguro de que desea eliminar permanentemente el grupo de Caja ?</p>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-raised btn-danger">Eliminar</button>
                    <button type="button" class="btn btn-raised btn-default" data-dismiss="modal">Cancelar</button>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts{

    <!-- ============================================================== -->
    <!-- Plugins for this page -->
    <!-- ============================================================== -->
    <!-- This is data table -->

    <script src="~/Content/assets/plugins/datatables/jquery.dataTables.min.js"></script>
    <!-- start - This is for export functionality only -->
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
    <script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js"></script>
    <script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.print.min.js"></script>

    <script type="text/javascript">


        $(function () {

            $('#example23').DataTable({
                "language": { "url": "../Content/assets/plugins/datatables/es.txt" },
                "order": [[2, 'asc']],
                'paging': true,
                'lengthChange': false,
                'searching': true,
                'ordering': true,
                'info': true,
                'autoWidth': true,
                'dom': 'Bfrtip',
                'buttons': [
                    'pdf'
                ]
            });
        });


        jQuery(function ($)
        {
            $('#myModalEliminar').on('show.bs.modal', function (e)
            {
                var id = $(e.relatedTarget).data().id;
                $(e.currentTarget).find('#Id').val(id);
            });
        });



    </script>
}