SAC/SAC/Controllers/RolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SAC.Models;
using Negocio.Servicios;
using Negocio.Modelos;
using AutoMapper;
using System.Web.Script.Serialization;
using Entidad.Models;

namespace SAC.Controllers
{
    public class RolController : BaseController
    {

        private ServicioConfiguracion servicioConfiguracion = new ServicioConfiguracion();
        private String JsonTreeView;
       
        private JavaScriptSerializer jsonString = new JavaScriptSerializer();

        public RolController()
        {
            servicioConfiguracion._mensaje = (msg_, tipo_) => CrearTempData(msg_, tipo_);
        }


        // GET: Rol
        public ActionResult Index()
        {
            ConfigRolModelView model = new ConfigRolModelView
            {
                Roles = Mapper.Map<List<RolModel>, List<RolModelView>>(servicioConfiguracion.GetAllRoles())               
            };
            return View(model);
        }
    
        [HttpPost, ActionName("AddAccionPorRol")]
        [ValidateAntiForgeryToken]
        public ActionResult AddAccionPorRol(RolModelView rolModelView)
        {
            var accionPorRol = new AccionPorRolModelView {
                                                    idRol = rolModelView.idRol,
                                                    idAccion = rolModelView.idAccionPorRol
                                                };           
            servicioConfiguracion.InsertarAccionPorRol(Mapper.Map<AccionPorRolModelView, AccionPorRolModel>(accionPorRol));
            return RedirectToAction("Edit", new { id = rolModelView.idRol });
         
        }

        [HttpPost, ActionName("DeleteAccionPorRol")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteAccionPorRol(int id)
        {
            var rol = (servicioConfiguracion.DeleteAccionPorRol(id));
            return RedirectToAction("Edit", new { id= rol.IdRol });
        }
     
        // GET: Rol/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Rol/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Rol/Create
        [HttpPost]
        public ActionResult Create(ConfigRolModelView model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    model.Rol.esAdministrador = false;
                    var rol = servicioConfiguracion.CrearRol(Mapper.Map<RolModelView, RolModel>(model.Rol));
                }
                return RedirectToAction("Index");

            }
            catch (Exception ex)
            {
                ViewBag.info = ex.InnerException;
                return View();
            }
        }

        public ActionResult Edit(int id)
        {
            var rol = Mapper.Map<RolModel, RolModelView>(servicioConfiguracion.GetRolPorId(id));
           // acciones que no esten en el menu y tampoco en el rol es decir podrian ser dadas de alta para el rol
            List<AccionModelView> accionesfuerademune  = Mapper.Map<List<AccionModel>, List<AccionModelView>>(servicioConfiguracion.GetAccionNoMenu(rol.idRol));
            rol.Acciones = accionesfuerademune;

            //accione por rol que no esten el el menu ?
            rol.AccionPorRol =Mapper.Map<List<AccionPorRolModel>,List<AccionPorRolModelView>>(servicioConfiguracion.GetAllAccionPorRol(rol.idRol));

       

            //acciones por rol que se encuentran el el menu
            List<MenuSideBarModel> menuSiderPorRol =servicioConfiguracion.GetMenuSidebarPorRol(rol.idRol); 
            //para chek los las acciones del menu que tiene el usuario
            ViewBag.JsonMenuSiderPorRol= getMenuSideBarModelSelect(menuSiderPorRol);
            /// menu
            ViewBag.JsonMenuSider = TreeView(servicioConfiguracion.GetMenuSidebar());

          
            return View("Edit", rol);
        }      
       
        public string getMenuSideBarModelSelect(List<MenuSideBarModel> model)
        {
            String[] menuIds = new String[model.Count];
            for (int i = 0; i < model.Count; i++)
            {
                    menuIds[i] = model[i].Titulo;
            }              
            return string.Join(",", menuIds);
        }
       
        public String TreeView(ICollection<MenuSideBarModel> model) {
            List<TreeViewModel> ListTreeView = new List<TreeViewModel>();
            foreach (var i in model)
            {
                TreeViewModel item = new TreeViewModel();
                item.text = i.Titulo;
                item.href = i.IdMenuSidebar.ToString();
                if (i.Group.Count > 0)
                {
                    List<TreeViewModel> ListNode = new List<TreeViewModel>();
                    foreach (var n in i.Group)
                    {
                        TreeViewModel nodo = new TreeViewModel();
                        nodo.text = n.Titulo;
                        nodo.href = n.IdMenuSidebar.ToString();
                        ListNode.Add(nodo);                      
                    }
                    item.nodes = ListNode;
                }
                ListTreeView.Add(item);
            }            
            JsonTreeView += jsonString.Serialize(ListTreeView);
            return JsonTreeView; 
        }
      
        // POST: Rol/Edit/5
        [HttpPost]
        public ActionResult Edit( RolModelView model )
        {
            try
            {
                //acciones q debe tener el usuario
                List<AccionModel> accionModels = getMenuSideBarModelCheck(model.MenuSidePorRol);                
                List<AccionPorRolModelView> ListAccionPorRol = new List<AccionPorRolModelView>();                
                foreach (var item in accionModels)
                {
                    // existe accion para el rol?
                    var apr = servicioConfiguracion.GetAccionPorRol(model.idRol,item.IdAccion);
                    if(apr is null) {
                        // agregar nuevo menu para el rol
                        AccionPorRolModelView accionPorRol = new AccionPorRolModelView {                         
                            idRol = model.idRol,
                            idAccion = item.IdAccion
                            };
                         ListAccionPorRol.Add(accionPorRol); 
                     }
                }

                QuitarMenusiderAlRol(accionModels, model.idRol);
                 model.AccionPorRol = ListAccionPorRol;

                 servicioConfiguracion.ActualizarRol(Mapper.Map<RolModelView, RolModel>(model));
                 ViewBag.info = "Se Guardo Correctamente";
                
                return RedirectToAction("Edit", model.idRol);
            }
            catch (Exception e)
            {
                return View();
            }
        }
    
        public List<AccionModel> getMenuSideBarModelCheck(string idMenusider)
        {
            var ids = idMenusider.Split(',').ToArray();
            List<AccionModel> accionDelMenu = new List<AccionModel>();
            foreach (var idmenusider in ids)
            {
                if(idmenusider.Length > 0)
                {
                    /// obtener por idmenusider la accion
                     var m =Mapper.Map<MenuSideBarModel,MenuSideBarModelView>( servicioConfiguracion.GetMenuSidebarPorIdFull(int.Parse(idmenusider)));                
                    accionDelMenu.Add(m.Accion);
                }             
            }
            return accionDelMenu;
        }

        public void QuitarMenusiderAlRol(List<AccionModel> accionModels ,int idRol )
        {
            //menu actual del usuario
            List<AccionModel> accionMenuSiderPorRol = servicioConfiguracion.GetAccionesEnMenuSidebarPorRol(idRol);
            // del menu nuevo que acciones no estan segun menu actual        
            var menuNuevo = (from a in accionModels  select a.IdAccion).ToList();
            var menuActual= (from m in accionMenuSiderPorRol select m.IdAccion).ToList();
            var result = (menuActual.Except(menuNuevo)).ToList();
            foreach (var item in result)
            {
                var acc = servicioConfiguracion.GetAccionPorRol(idRol, item);
                if(acc != null)
                {
                    DeleteAccionPorRol(acc.idRolPorAccion);
                }
            }

        }

        [HttpPost, ActionName("Delete")]
        public JsonResult Delete(int Id)
        {
           // servicioConfiguracion.DeleteMenusidebar(Id);
            return Json(new { status = "Success" });
        }

        private SelectList selectListAccion(List<AccionModelView> acc)
        {
            Dictionary<int, string> dic = new Dictionary<int, string>();
            foreach (var item in acc)
            {
                dic.Add(item.IdAccion, item.Controlador + " - " + item.Nombre);
            }
            return new SelectList(dic, "Key", "Value");
        }


    }
}

SAC/SAC/Views/Rol/DeleteAccionPorRol.cshtml
@model SAC.Models.RolModelView
@{
    ViewBag.Title = "Eliminar";
}

<h2>Eliminar Accion por Rol</h2>

<h3>¿Estás seguro que quieres eliminar esto?</h3>
<div>
    <h4>Instructor</h4>
    <hr />
    <dl class="dl-horizontal">
        @*<dt>
            @Html.DisplayNameFor(model => model.OfficeAssignment.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OfficeAssignment.Location)
        </dd>*@

      
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SAC/SAC/Views/Rol/Edit.cshtml
@model SAC.Models.RolModelView
@{
    ViewBag.Title = "Roles";
}
<link href="/Content/assets/plugins/switchery/dist/switchery.min.css" rel="stylesheet" />
<link href="/Content/assets/css/pages/floating-label.css" rel="stylesheet">



<div class="row page-titles">
    <div class="col-md-5 align-self-center">
        <h3 class="text-themecolor">Roles</h3>
    </div>

</div>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">

                @using (Html.BeginForm("Edit", "Rol", FormMethod.Post, new { @class = "floating-labels ", novalidate = true }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.idRol)
                   
                    @Html.HiddenFor(model => model.MenuSidePorRol)

                    <input id="JsonMenuSiderPorRol"
                           name="JsonMenuSiderPorRol"
                           type="hidden"
                           value="@ViewBag.JsonMenuSiderPorRol" />

                    <input id="JsonMenuSider"
                           name="JsonMenuSider"
                           type="hidden"
                           value="@ViewBag.JsonMenuSider" />
                    
                    <div class="row ">
                        <div class="col-xlg-10 col-lg-10 col-md-10 ">
                            <div class="row ">
                                <div class="col-xlg-12 col-lg-12 col-md-12">

                                    <h4 class="card-title">Roles del Sistema </h4>
                                    <h6 class="card-subtitle"> Se configuran todas las acciones disponibles del sistema, puede agregar ó eliminar los items </h6>
                                </div>
                            </div>

                            <div class="row m-t-40">
                                <div class="col-xlg-4 col-lg-4 col-md-4">

                                    <div class="form-group m-b-30">
                                        @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                                        <span class="bar"></span>
                                        <label for="rol_descripcion">Nombre de Rol</label>
                                    </div>

                                </div>

                                <div class="col-xlg-4 col-lg-4 col-md-4">

                                    <div class="checkbox">

                                        <div class="form-group m-b-30">
                                            Es Administrador ?
                                            <input type="checkbox" @Html.Raw((Model.esAdministrador) ? "checked" : " ") id="General" class="js-switch js-check-esAdministrador" data-color="#26c6da" data-size="small" />
                                            @Html.HiddenFor(model => model.esAdministrador)
                                        </div>

                                    </div>
                                </div>


                            </div>

                        </div>


                    </div>

                  
                    <div class="row">
                        @*<div class="col-xlg-12 col-lg-12 col-md-12"></div>*@
                        <div class="col-xlg-12 col-lg-12 col-md-12 bg-light-part ">
                            <div class="row">

                                <div class="col-xlg-6 col-lg-6 col-md-6  m-t-20">

                                    <div class="card">
                                        <div class="card-body">
                                            <h5 class="card-title">Menu Inicio habilitado para el Rol</h5>
                                            <h5 class="card-subtitle mb-2 text-muted"></h5>
                                            <p class="card-text"> </p>
                                            <h6 class="card-subtitle mb-2 text-muted">Habilite las opciones y seleccione guardar para confirmar los cambios</h6>
                                            <div id="treeview-checkable" class=""></div>
                                        </div>
                                    </div>

                                </div>

                                <div class="col-xlg-6 col-lg-6 col-md-6  m-t-20">

                                    <div class="card">
                                        <div class="card-body">
                                            <h5 class="card-title">Acciones permitidas para el rol</h5>
                                            <h6 class="card-subtitle">
                                                Acciones que no se encuentran en el Menu Inicio
                                                y necesita restringir para el rol. Por defecto se encuentran todas habilitadas.
                                            </h6>
                                            <table id="tblMenusidebar" class="table table-hover no-wrap">
                                                <thead>
                                                    <tr>
                                                        <th>
                                                            Acciones
                                                        </th>
                                                        <th>
                                                            <button type="button" class="btn btn-secondary btn-sm pull-right" data-toggle="modal" data-target="#add-AccionPorRol">
                                                                <i class="ti-menu"></i> Agregar Acción
                                                            </button>

                                                        </th>
                                                        <th></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    @if (Model.AccionPorRol.Count() > 0)
                                                        {
                                                            foreach (var item in Model.AccionPorRol)
                                                            {
                                                                <tr>
                                                                    <td>
                                                                        @Html.DisplayFor(modelItem => item.Accion.Descripcion)
                                                                    </td>

                                                                    <td>
                                                                        <input type="submit" value="Eliminar" formaction="@Url.Action("DeleteAccionPorRol", "Rol", new { id = item.idRolPorAccion })" class="btn btn-primary font-10" data-toggle="tooltip" data-original-title="Se eliminara el registro..." />
                                                                    </td>
                                                                </tr>
                                                            }
                                                        }
                                                  
                                                    else
                                                    {
                                                        <tr>
                                                            <td>
                                                                No se encontraron registros...
                                                            </td>
                                                        </tr>
                                                    }
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>

                                </div>

                            </div>

                        </div>


                    </div>

                    <div class="row text-center">
                        <div class="col-xlg-12 col-lg-12 col-md-12 m-t-40">
                            <div class="form-group">
                                <a href="@Url.Action("Index", "Rol" )" class="btn btn-rounded  btn-secondary "> Volver </a>
                                <input type="submit" value="Guardar" class="btn btn-rounded  btn-success" />
                                <a id="btnEliminar" href="#" class="btn btn-rounded btn-danger  "><i class="fa fa-times"></i> Eliminar </a>
                            </div>
                        </div>
                    </div>


                    <!--.modal --->
                    <div id="add-AccionPorRol" class="modal fade in" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h4 class="modal-title" id="myModalLabel">Nueva Accion para el rol   @Html.Raw(Model.descripcion) </h4>
                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>

                                </div>
                                <div class="modal-body">
                                    <div class="floating-labels m-t-30">
                                        <div class="form-group m-b-30">

                                            @Html.DropDownListFor(model => model.idAccionPorRol,
                                                          (IEnumerable<SelectListItem>)(new SelectList(Model.Acciones.Select(x => new { Value = x.IdAccion, Text = x.Descripcion }),
                                                                         "Value", "Text"))
                                                          , "Seleccionar Accion...", new { @class = "form-control" })
                                        </div>
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <input type="submit" value="Agregar" formaction="@Url.Action("AddAccionPorRol", "Rol")" class="btn btn-primary" />
                                    <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Cancelar</button>
                                </div>
                            </div>

                        </div>
                    </div>
                    <!-- /.modal- -->

                    <!-- modal Eliminar --->
                    <div class="modal fade" id="myModal">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <a href="#" class="close" data-dismiss="modal">&times;</a>
                                    <h3 class="modal-title">Eliminar</h3>
                                </div>
                                <div class="modal-body">
                                    <h4>¿Está seguro de que desea eliminar?</h4>

                                </div>
                                <div class="modal-footer">
                                    <a href="#" class="btn btn-default btn-sm" data-dismiss="modal">Cancelar</a>
                                    <a id="btnConfirmEliminar" href="#" class="btn btn-success btn-sm">Confirmar</a>
                                </div>

                            </div>

                        </div>

                    </div>
                    <!-- /.modal- -->
                }

            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script src="~/Content/assets/plugins/switchery/dist/switchery.min.js"></script>
    <!-- Treeview Plugin JavaScript -->
    <script src="~/Content/assets/plugins/bootstrap-treeview-master/dist/bootstrap-treeview.min.js"></script>   
    <script src="~/Scripts/TreeView/TreeView.js"></script>
    <script>
        jQuery(document).ready(function () {
            // Switchery
            var elems = Array.prototype.slice.call(document.querySelectorAll('.js-switch'));
            $('.js-switch').each(function () {
                new Switchery($(this)[0], $(this).data());
            });

            var changeCheckbox = document.querySelector('.js-check-esAdministrador')
                , changeField = document.querySelector('.js-check-esAdministrador-field');
            changeCheckbox.onchange = function () {
                $("input[type='hidden'][name='esAdministrador']").val(changeCheckbox.checked);
            };


            $("#btnEliminar").click(function (e) {
                e.preventDefault();
                $("#myModal").modal('show');
            });

            $("#btnConfirmEliminar").click(function (e) {
                e.preventDefault();
                var x = $("input[type='hidden'][name='idRol']").val();
                $.ajax({
                    type: "POST",
                    url: "/Rol/Delete",
                    data: { Id: x },
                    success: function (result) {
                        $("#myModal").modal("hide");
                    }
                })
            });

        });
    </script>
    <script src="~/Content/assets/plugins/styleswitcher/jQuery.style.switcher.js"></script>

}

SAC/SAC/Views/Rol/Index.cshtml
@model SAC.Models.ConfigRolModelView
@{
    ViewBag.Title = "Gestión de Rol";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!-- page css -->
<link href="/Content/assets/css/pages/floating-label.css" rel="stylesheet">
<style>
    .dataTables_wrapper .dataTables_paginate .paginate_button {
        padding: 0.1em 1em;
    }
    .table td, .table th {
        padding: .25rem;
    }
</style>


<!-- ============================================================== -->
<!-- Bread crumb and right sidebar toggle -->
<!-- ============================================================== -->

<div class="row page-titles">
    <div class="col-md-5 align-self-center">
        <h3 class="text-themecolor">Roles</h3>
    </div>
    @*<div class="col-md-7 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                <li class="breadcrumb-item">Apps</li>
                <li class="breadcrumb-item active">mailbox</li>
            </ol>
        </div>*@

</div>

<!-- ============================================================== -->
<!-- End Bread crumb and right sidebar toggle -->
<!-- ============================================================== -->


<!-- ============================================================== -->
<!-- Start Page Content -->
<!-- ============================================================== -->

<div class="col-xlg-12 col-lg-12 col-md-12">
    @using (Html.BeginForm(FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-10">
                        <h4 class="card-title">Roles de Sistemas </h4>
                        <h6 class="card-subtitle"> Permite agrupar funciones del sistema para asignar a un grupo de usuario </h6>
                    </div>
                    <div class="col-md-2 pull-right">
                        <button type="button" class="btn btn-secondary btn-sm " data-toggle="modal" data-target="#add-rol">
                            <i class="ti-menu"></i> Agregar Rol
                        </button>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                     
                    </div>
                </div>

                <div class="table-responsive">
                    <table id="tblMenusidebar" class="table stylish-table">
                        <thead>
                            <tr>
                                <th>
                                    Rol
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model.Roles.Count() > 0)
                            {
                                foreach (var item in Model.Roles)
                                {
                                    <tr>
                                        <td> @Html.DisplayFor(modelItem => item.descripcion) </td>
                                        <td>
                                            <a href="@Url.Action("Edit", "Rol",new { id = item.idRol })" class="btn btn-primary font-10" data-toggle="tooltip" data-original-title="Detalles">más </a>
                                        </td>
                                    </tr>
                                }
                            }else{
                                <tr>
                                    <td>
                                        No se encontraron registros...
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>

                <!--.modal- -->
                <div id="add-rol" class="modal fade in" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title" id="myModalLabel">Nuevo Rol de Sistema </h4>
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            </div>
                            <div class="modal-body">
                                <div class="floating-labels m-t-30">
                                    <div class="form-group m-b-40">
                                        @Html.EditorFor(model => model.Rol.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                                        <span class="bar"></span>
                                        <label for="accion_nombre">Nombre de Rol</label>
                                    </div>
                                    @*<div class="form-group m-b-30">
                                        @Html.EditorFor(model => model.Rol.idHome, new { htmlAttributes = new { @class = "form-control" } })
                                        <span class="bar"></span>
                                        <label for="acccion_controlador">Nombre del Controlador </label>
                                        <span class="help-block"><small>EJ.: Evento para EventoController </small></span>
                                    </div>*@
                                </div>
                            </div>
                            <div class="modal-footer">
                                <input type="submit" value="Guardar" formaction="@Url.Action("Create", "Rol")" class="btn btn-primary" />
                                <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Cancelar</button>
                            </div>
                        </div>

                    </div>
                </div>
                <!-- /.modal- -->
            </div>
        </div>
       
    }

</div>





<!-- ============================================================== -->
<!-- End PAge Content -->
<!-- ============================================================== -->

@section Scripts{

    <!-- This is data table -->
    <script src="/Content/assets/plugins/datatables/jquery.dataTables.min.js"></script>
    <!-- start - This is for export functionality only -->
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
    <script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js"></script>
    <script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.print.min.js"></script>



    <script type="text/javascript">
        $(document).ready(function () {
        });



            //$('#tblAccion').DataTable({
            //    dom: 'Bfrtip',
            //    buttons: [
            //        'pdf', 'print'
            //    ]
            //});
            //$('#tblRol').DataTable({
            //    dom: 'Bfrtip',
            //    buttons: [
            //        'pdf', 'print'
            //    ]
            //});
            //$('#tblMenusidebar').DataTable({
            //    dom: 'Bfrtip',
            //    buttons: [
            //        'pdf', 'print'
            //    ]
            //    });

            //});




            //$('#example23').DataTable({
            //    dom: 'Bfrtip',
            //    buttons: [
            //        'pdf', 'print'
            //    ]
            //});

    </script>

}