SAC/SAC/Controllers/ProveedorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//agregadas
using AutoMapper;
using Negocio.Modelos;
using Negocio.Servicios;
using SAC.Atributos;
using SAC.Models;
using System.Web.Routing;


namespace SAC.Controllers
{
    public class ProveedorController : BaseController
    {

        private ServicioProveedor servicioProveedor = new ServicioProveedor();

        public ProveedorController()
        {
            servicioProveedor._mensaje = (msg_, tipo_) => CrearTempData(msg_, tipo_);
        }

        // GET: Accion
        public ActionResult Index()
        {
            List<ProveedorModelView> model = Mapper.Map<List<ProveedorModel>, List<ProveedorModelView>>(servicioProveedor.GetAllProveedor());
            return View(model);
        }

        // GET: Accion/Create
        public ActionResult Agregar()
        {
            CargarCombos();
            return View();
        }
        // GET: Accion/Create
        public ActionResult Editar(int _id)
        {
            CargarCombos();

            ProveedorModelView oProveedorModel = new ProveedorModelView();
            oProveedorModel = Mapper.Map<ProveedorModel, ProveedorModelView>(servicioProveedor.GetProveedor(_id));

            //estod deberia ir en el negocio pero el automapper no me deja 01/12/2020
            //ServicioLocalidad oServicioLocalidad = new ServicioLocalidad();
            CargarProvincia(oProveedorModel.IdPais ?? 0);
            CargarLocalidad(oProveedorModel.IdProvincia ?? 0 );

            return View(oProveedorModel);
        }
        

        [HttpPost]
        public ActionResult Agregar(ProveedorModelView oProveedorModelView)
        {
            CargarCombos();
            int respuesta = -1;
            try
            {
                if (!ModelState.IsValid)
                {

                    var query = (from state in ModelState.Values
                                 from error in state.Errors
                                 select error.ErrorMessage).ToList();

                    return View(oProveedorModelView);
                }
                else
                {
                    var datosUsuario = (UsuarioModel)System.Web.HttpContext.Current.Session["currentUser"];
                    ProveedorModel oProveedor = new ProveedorModel();
                    var oProveedorModel = Mapper.Map<ProveedorModelView, ProveedorModel>(oProveedorModelView);

                    oProveedor.Nombre = oProveedorModel.Nombre;
                    oProveedor.Direccion = oProveedorModel.Direccion;
                    oProveedor.Telefono = oProveedorModel.Telefono;
                    oProveedor.IdPais = oProveedorModel.IdPais;
                    oProveedor.IdProvincia= oProveedorModel.IdProvincia;
                    oProveedor.IdLocalidad = oProveedorModel.IdLocalidad;
                    oProveedor.IdCodigoPostal = oProveedorModel.IdCodigoPostal;
                    oProveedor.Email = oProveedorModel.Email;
                    oProveedor.IdImputacionProveedor = oProveedorModel.IdImputacionProveedor;
                   
                    oProveedor.IdTipoIva = oProveedorModel.IdTipoIva;
                    oProveedor.Cuit = oProveedorModel.Cuit;
                    oProveedor.IdImputacionFactura = oProveedorModel.IdImputacionFactura;
                    oProveedor.IdTipoProveedor = oProveedorModel.IdTipoProveedor;
                    oProveedor.IdTipoMoneda = oProveedorModel.IdTipoMoneda;
                    oProveedor.Observaciones = oProveedorModel.Observaciones;
                    oProveedor.Activo = true;
                    oProveedor.IdUsuario = datosUsuario.IdUsuario;//hay que poner el id del usuario logueado
                    oProveedor.UltimaModificacion = DateTime.Now.Date;

                    respuesta = servicioProveedor.GuardarProveedor(oProveedor);

                    if (respuesta == 0) //grabo
                    {
                        servicioProveedor._mensaje("El país se registró correctamente", "ok");
                    }
                    else if (respuesta == -1) // paso algo
                    {
                        servicioProveedor._mensaje("El país ingresado No se pudo registrar", "error");
                    }
                    else //ya existe
                    {
                        servicioProveedor._mensaje("El país que intenta resitrar ya se encuentra cargado", "error");
                    }
                    return RedirectToAction("Index");
                }

            }
            catch (Exception ex)
            {
                servicioProveedor._mensaje("Ops!, Ocurrio un error. Comuníquese con el administrador del sistema", "error");
                return View(oProveedorModelView);
            }
        }


        [HttpPost]
        public ActionResult Editar(ProveedorModelView oProveedorModelView)
        {
            //CargarCombos();

            try
            {
                if (!ModelState.IsValid)
                {
                    return View(oProveedorModelView);
                }
                else
                {
                    var datosUsuario = (UsuarioModel)System.Web.HttpContext.Current.Session["currentUser"];

                    ProveedorModel oProveedorModel = new ProveedorModel();
                    var oProveedor = Mapper.Map<ProveedorModelView, ProveedorModel>(oProveedorModelView);
                    oProveedorModel.Id = oProveedor.Id;
                    oProveedorModel.Nombre = oProveedor.Nombre;
                    oProveedorModel.Direccion = oProveedor.Direccion;
                    oProveedorModel.Telefono = oProveedor.Telefono;
                    oProveedorModel.IdPais = oProveedor.IdPais;
                    oProveedorModel.IdProvincia = oProveedor.IdProvincia;
                    oProveedorModel.IdLocalidad = oProveedor.IdLocalidad;
                    oProveedorModel.IdCodigoPostal = oProveedor.IdCodigoPostal;
                    oProveedorModel.Email = oProveedor.Email;
                    oProveedorModel.IdImputacionProveedor = oProveedor.IdImputacionProveedor;

                    oProveedorModel.IdTipoIva = oProveedor.IdTipoIva;
                    oProveedorModel.Cuit = oProveedor.Cuit;
                    oProveedorModel.IdImputacionFactura = oProveedor.IdImputacionFactura;
                    oProveedorModel.IdTipoProveedor = oProveedor.IdTipoProveedor;
                    oProveedorModel.IdTipoMoneda = oProveedor.IdTipoMoneda;
                    oProveedorModel.Observaciones = oProveedor.Observaciones;
                    oProveedorModel.Activo = true;
                    oProveedorModel.IdUsuario = datosUsuario.IdUsuario;//hay que poner el id del usuario logueado
                    oProveedorModel.UltimaModificacion = DateTime.Now.Date;

                    servicioProveedor.ActualizarProveedor(oProveedorModel);

                    return RedirectToAction("Index");
                }
            }

            catch (Exception ex)
            {
                servicioProveedor._mensaje("Ops!, Ocurrio un error. Comuníquese con el administrador del sistema", "error");
                return View(oProveedorModelView);
            }
        }



        //busco las provincias
        public JsonResult GetlistaProvincias(int idPais)
        {
            //string a = "dsaasdasdad";
            ServicioProvincia servicioProvincia = new ServicioProvincia();
            List<ProvinciaModelView> ListaProvincia = Mapper.Map<List<ProvinciaModel>, List<ProvinciaModelView>>(servicioProvincia.GetAllProvinciasNombreId(idPais));
            return Json(ListaProvincia, JsonRequestBehavior.AllowGet);
        }

        //busco las provincias
        public JsonResult GetlistaLocalidades(int idProvincia)
        {
            //string a = "dsaasdasdad";
            ServicioLocalidad servicioLocalidad = new ServicioLocalidad();
            List<LocalidadModelView> ListaLocalidad = Mapper.Map<List<LocalidadModel>, List<LocalidadModelView>>(servicioLocalidad.GetAllLocalidads(idProvincia));
            return Json(ListaLocalidad, JsonRequestBehavior.AllowGet);
        }

        //busco el codigo postal de la localidad
        public JsonResult GetCodigoPostal(int idLocalidad)
        {
            ServicioLocalidad servicioLocalidad = new ServicioLocalidad();
            var CpLocalidad = servicioLocalidad.GetCodigoPostal(idLocalidad);
            return Json(CpLocalidad, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCuentaCorriente(int oIdProveedor)
        {
            return Json(1, JsonRequestBehavior.AllowGet);
        }


        public void CargarCombos()
        {
            CargarPais();
            CargarTipoIva();
           // CargarSubRubro();
            CargarTipoMoneda();
            CargarTipoProveedor();
        }
       

        [HttpPost]
        public ActionResult CargarImputacion()
        {
            ServicioImputacion oServicioImputacion = new ServicioImputacion();
            List<ImputacionModelView> ListaImputacion = Mapper.Map<List<ImputacionModel>, List<ImputacionModelView>>(oServicioImputacion.GetAllImputacions());
            return PartialView("_TablaImputacion", ListaImputacion);
        }

        [HttpPost]
        public ActionResult Eliminar(int idProveedor)
        {
            try
            {
                servicioProveedor.Eliminar(idProveedor);
                servicioProveedor._mensaje("El proveedor se eliminó correctamente", "ok");
            }
            catch (Exception ex)
            {
               servicioProveedor._mensaje("Ops!, Ocurrio un error. Comuníquese con el administrador del sistema", "error");
            }

            return RedirectToAction("Index");
        }


        public void CargarPais()
        {
            ServicioPais servicioPais = new ServicioPais();

SAC/SAC/Views/Proveedor/Index.cshtml
@model List<SAC.Models.ProveedorModelView>

@{
    ViewBag.Title = "Lista Proveedores";
    Layout = "~/Views/Shared/_Layout.cshtml";

}



<!-- ============================================================== -->
<!-- Bread crumb and right sidebar toggle -->
<!-- ============================================================== -->
<div class="row page-titles m-t-40">
    <div class="col-md-5 align-self-center">
        <h3 class="text-themecolor">Lista de Proveedores</h3>
    </div>

</div>
<div class="row">
    <div class="col-xlg-12 col-lg-12 col-md-12">
        <div class="card">
            <div class="card-body">

                <h4 class="card-title">Exportar datos</h4>
                <h6 class="card-subtitle">Formato de salida: PDF</h6>

                <div class="row m-t-20 m-b-40">                   
                    <div class="col-md-12">
                        @Html.ActionLink("Nuevo", "Agregar", "Proveedor", new { @class = "btn btn-secondary btn-sm" })
                    </div>
                </div>
                              
                <div class="table-responsive">
                    <table id="TblProveedor" class="table stylish-table">

                        <thead>
                            <tr>
                                <th> Nombre</th>
                                <th> Cuit</th>
                                <th> Tipo</th>
                                <th>Telefono</th>
                                <th>Email</th>
                                <th>Operaciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                            <tr>
                                <td>@Html.DisplayFor(modelItem => item.Nombre)</td>
                                <td>@Html.DisplayFor(modelItem => item.Cuit)</td>
                                <td>@Html.DisplayFor(modelItem => item.TipoProveedor.Descripcion)</td>
                                <td>@Html.DisplayFor(modelItem => item.Telefono)</td>
                                <td>@Html.DisplayFor(modelItem => item.Email)</td>

                                <td>
                                    @Html.ActionLink(" ", "Editar", "Proveedor", new { _id = @item.Id }, new { @class = "btn btn-primary fa fa-pencil-square-o" })
                                    @Html.ActionLink(" ", "Eliminar", "Proveedor", new { _id = @item.Id }, new { @class = "btn btn-danger fa fa-trash-o", onclick = "AsigarConfirmacion(" + @item.Id + ")" })
                                </td>
                            </tr>
                            }
                        </tbody>
                    </table>


                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="ModalConfirmacion" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Aviso</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="modal-body">
                <h3> ¿Está seguro que desea eliminar el proveedor seleccionado?</h3>
            </div>


            <div style="padding:1em;">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <button type="button" onclick="Eliminar()" class="btn btn-primary">Aceptar</button>

            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="ModalAlerta" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-warning">
                <h5 class="modal-title" id="exampleModalLabel">Aviso Importante</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="modal-body">
                <h2> El proveedor seleccionado no puede ser eliminado porque la cuenta corriente tiene saldo favorable o desfavorable</h2>
            </div>

            <div class="modal-footer text-right">
                <div style="padding:1em;">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
            
        </div>
    </div>
</div>

@* crea un formulario para ir al controlador *@
@using (Html.BeginForm("Eliminar", "Proveedor", FormMethod.Post, new { @id = "frmEliminar" }))
{
    @Html.Hidden("idProveedor");
}


<script>
    function AsigarConfirmacion(idProveedor) {
        event.preventDefault();

        $.get("/Proveedor/GetCuentaCorriente/", { oIdProveedor: idProveedor }, function (data) {
            if (data == 0) {
                document.getElementById("idProveedor").value = idProveedor;
                $("#ModalConfirmacion").modal('show');
            }
            else {
                $("#ModalConfirmacion").modal('hide');
                $("#ModalAlerta").modal('show');
            }
        });
    }

    //esto es para mostrar el modal con ajaxlink
    //var parameter;
    //$("#deleteActionLink").on("click", function () {
    //    //save your parameter in variable
    //    parameter = $("#deleteActionLink").data("parameter");
    //    document.getElementById("idPais").value = parameter;
    //});

    function Eliminar() {
        var frmEliminar = document.getElementById("frmEliminar");
        frmEliminar.submit();
    }

</script>

@section Scripts{

    <!-- This is data table -->
    <script src="/Content/assets/plugins/datatables/jquery.dataTables.min.js"></script>
    <!-- start - This is for export functionality only -->
    <script src="~/Content/assets/plugins/datatables/jsTable/dataTables.buttons.min.js"></script>
    <script src="~/Content/assets/plugins/datatables/jsTable/buttons.flash.min.js"></script>
    <script src="~/Content/assets/plugins/datatables/jsTable/jszip.min.js"></script>
    <script src="~/Content/assets/plugins/datatables/jsTable/pdfmake.min.js"></script>
    <script src="~/Content/assets/plugins/datatables/jsTable/vfs_fonts.js"></script>
    <script src="~/Content/assets/plugins/datatables/jsTable/buttons.html5.min.js"></script>
    <script src="~/Content/assets/plugins/datatables/jsTable/buttons.print.min.js"></script>



    <script type="text/javascript">
        $(document).ready(function () {
            $('#TblProveedor').DataTable({
                dom: 'Bfrtip',
                buttons: [
                    'pdf'
                ]
            });
        });



    </script>

}